### PR TITLE
Basic macOS (aka OS X) app

### PR DESCRIPTION
**Pull request by melchor629**
Supports OS X 10.9 or higher
Written in Swift

### CODE REVIEW

**Comment by Ilshidur** [comment]
I think we should replace the `http://www[...]` part to `https://[...]` (in _ViewController.swift_) because the "lol-item-sets-generator.org" used HTTPS by default, and using HTTP would be an useless redirect.

Also, as I am a Windows user I didn't tested it but before merging I would like to know if there is a 60 seconds limit on auto downloads like on the Windows app. Are the users able to download the sets regularly without DDoSing the server ?

**Comment by melchor629** [comment]
Now uses https. Also, if you want to download a version that you have, the button is deactivated, so nobody cannot make a DDoS attack by clicking the button a lot. And, if you can download, when the button is pressed, it gets deactivated as well. Furthermore, in background, checks if there's a new version of the items, and let you download if it's available.

All this changes have been pushed.

**Comment by Ilshidur** [comment]
This is some awesome work. Thank you !

The app looks complete, I can now merge the pull request if you think it is O.K.

**Comment by melchor629** [comment]
You can merge it without any problem

**Pull request merged**
